manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/jahkamren/zmk-custom
  projects:
    - name: zmk-custom
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
